### ISSUE TITLE
How to run quorum-profiling on local quorum network?

### ISSUE THREAD

**Issue by daemonsloth** [ConsenSys/quorum-profiling#19]
I've built a quorum network locally on my machine using the following tutorial:
https://consensys.net/docs/goquorum/en/stable/tutorials/private-network/create-ibft-network/

Basically, I want to run few tests on this network and I believe quorum-profiling will be a good tool for that. I saw the packages for quorum-profiling on this github repository and it had some docker installation commands. I'm not sure if that will work with this local network I created since I didn't have to use Docker to create this network. (Also, I've no prior experience with docker, so can't say)

Can anybody help me with this?

**Comment by baptiste-b-pegasys** [comment]
Hello, sorry for the late response.

The local setup is in the 'scripts' directory.

Yet, it is better to have one directory per setup you want, I provide you one with local.zip.

1. from scripts, start docker-compose environment, you should get grafana up and running
2. from local, configure the account addresses, ip, port in the network.properties and host_acc.csv files, then launch `./run.sh`

the public.jmx is profiling the first node only, you can adapt other jmx as you want. I recommend to use wireshark for debugging the http requests.

[https://app.zenhub.com/files/247661029/20279c27-95b8-4b78-a553-21333bdb1d45/download](https://app.zenhub.com/files/247661029/20279c27-95b8-4b78-a553-21333bdb1d45/download)
